- name: add Rabbitmq signing key
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present

- name: add apt repository for Rabbitmq and Erlang
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: bintray.rabbitmq.list
  loop:
    - "deb https://dl.bintray.com/rabbitmq-erlang/debian {{ debian_distribution }} erlang"
    - "deb https://dl.bintray.com/rabbitmq/debian {{ debian_distribution }} main"

- name: apt install rabbitmq-server
  apt:
    name: "rabbitmq-server={{ rabbitmq_version }}"
    update_cache: yes
    state: present

- name: add Rabbitmq config and enabled_plugins
  template:
    src: "templates/{{ item }}"
    dest: "/etc/rabbitmq/{{ item }}"
  loop:
    - rabbitmq.conf
    - enabled_plugins
  notify:
    - restart rabbitmq-server
